import { markdown } from './markdown';

export interface TextSpan {
  text: string;
  bold?: boolean;
  italic?: boolean;
  code?: boolean;
  strike?: boolean;
  underline?: boolean;
  highlight?: boolean;
  subscript?: boolean;
  superscript?: boolean;
  url?: string;
  checkbox?: boolean;
  emoji?: boolean;
  image?: { src: string; alt: string };
  footnoteId?: number;
}

export interface DocumentBlock {
  kind: 'heading' | 'paragraph' | 'code' | 'diagram' | 'table' | 'rule';
  spans: TextSpan[];
  level?: number;
  indent?: number;
  quote?: boolean;
  callout?: string;
  definitionTerm?: boolean;
  language?: string;
  source?: string;
  rows?: TextSpan[][][];
  alignments?: Array<'left' | 'center' | 'right'>;
  list?: { id: number; ordered: boolean; start: number; index: number; level: number; first: boolean };
  footnoteId?: number;
}

type Token = ReturnType<typeof markdown.parse>[number];

function inlineSpans(tokens: Token[]): TextSpan[] {
  const spans: TextSpan[] = [];
  const active: Record<string, number> = {};
  const flags: Record<string, keyof TextSpan> = {
    strong: 'bold', em: 'italic', s: 'strike', ins: 'underline', mark: 'highlight',
    sub: 'subscript', sup: 'superscript',
  };
  const links: string[] = [];
  const style = (): TextSpan => ({
    text: '', ...Object.fromEntries(Object.entries(flags).filter(([tag]) => active[tag] > 0).map(([, flag]) => [flag, true])),
    url: links.at(-1),
  });
  for (const token of tokens) {
    const match = /^(.*)_(open|close)$/.exec(token.type);
    if (match && flags[match[1]]) {
      active[match[1]] = (active[match[1]] || 0) + (match[2] === 'open' ? 1 : -1);
    } else if (token.type === 'link_open') links.push(String(token.attrGet('href') || ''));
    else if (token.type === 'link_close') links.pop();
    else if (token.type === 'softbreak') spans.push({ ...style(), text: ' ' });
    else if (token.type === 'hardbreak') spans.push({ text: '\n' });
    else if (token.type === 'image') {
      spans.push({ ...style(), image: { src: String(token.attrGet('src') || ''), alt: token.content } });
    } else if (token.type === 'wikilink') {
      const [target, label] = token.content.split('|', 2);
      spans.push({ ...style(), text: label || target });
    } else if (token.type === 'footnote_ref') {
      const id = Number(token.meta?.id) + 1;
      spans.push({ ...style(), text: String(id), footnoteId: id, superscript: true });
    } else if (token.type === 'html_inline') {
      // These are generated by the task-list plugin; user HTML is escaped by markdown.
      if (/^<input\b[^>]*type="checkbox"/.test(token.content)) {
        spans.push({ text: '', checkbox: /\bchecked(?:=|\s|>)/.test(token.content) });
      }
    } else if (token.type === 'text' || token.type === 'code_inline' || token.type === 'emoji') {
      if (token.type === 'text' && /\p{Extended_Pictographic}|\p{Regional_Indicator}|\u20E3/u.test(token.content)) {
        let text = '';
        for (const { segment } of new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment(token.content)) {
          if (/\p{Extended_Pictographic}|\p{Regional_Indicator}|\u20E3/u.test(segment)) {
            if (text) spans.push({ ...style(), text });
            spans.push({ ...style(), text: segment, emoji: true }); text = '';
          } else text += segment;
        }
        if (text) spans.push({ ...style(), text });
      } else spans.push({ ...style(), text: token.content, code: token.type === 'code_inline', emoji: token.type === 'emoji' });
    }
  }
  return spans;
}

/** The export and on-screen preview interpret exactly the same Markdown dialect. */
export function parseDocument(content: string): DocumentBlock[] {
  const tokens = markdown.parse(content, {});
  const blocks: DocumentBlock[] = [];
  const lists: Array<{ id: number; ordered: boolean; start: number; index: number; pending: boolean }> = [];
  const callouts: string[] = [];
  let heading = 0, quote = 0, definition = 0, listId = 0;
  let definitionTerm = false;
  let footnoteId: number | undefined;
  const context = () => ({
    indent: lists.length + definition, quote: quote > 0, callout: callouts.at(-1), footnoteId,
  });
  function listContext(): DocumentBlock['list'] {
    const list = lists.at(-1);
    if (!list) return undefined;
    const result = { ...list, level: lists.length - 1, first: list.pending };
    list.pending = false;
    return result;
  }
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.type === 'heading_open') heading = Number(token.tag.slice(1));
    else if (token.type === 'heading_close') heading = 0;
    else if (token.type === 'blockquote_open') quote++;
    else if (token.type === 'blockquote_close') quote--;
    else if (token.type === 'dt_open') definitionTerm = true;
    else if (token.type === 'dt_close') definitionTerm = false;
    else if (token.type === 'dd_open') definition++;
    else if (token.type === 'dd_close') definition--;
    else if (token.type.startsWith('container_') && token.nesting === 1) callouts.push(token.type.slice(10, -5));
    else if (token.type.startsWith('container_') && token.nesting === -1) callouts.pop();
    else if (token.type === 'footnote_open') footnoteId = Number(token.meta?.id) + 1;
    else if (token.type === 'footnote_close') footnoteId = undefined;
    else if (token.type === 'bullet_list_open' || token.type === 'ordered_list_open') {
      const start = Number(token.attrGet('start') || 1);
      lists.push({ id: listId++, ordered: token.type === 'ordered_list_open', start, index: start - 1, pending: false });
    } else if (token.type === 'bullet_list_close' || token.type === 'ordered_list_close') lists.pop();
    else if (token.type === 'list_item_open' && lists.length) {
      lists[lists.length - 1].index++;
      lists[lists.length - 1].pending = true;
    } else if (token.type === 'inline') {
      blocks.push({ kind: heading ? 'heading' : 'paragraph', level: heading,
        spans: inlineSpans(token.children || []), ...context(), list: listContext(), definitionTerm });
    } else if (token.type === 'fence' || token.type === 'code_block') {
      const language = token.info.trim().split(/\s+/, 1)[0];
      const source = token.content.replace(/\n$/, '');
      blocks.push({ ...context(), list: listContext(), kind: language === 'mermaid' ? 'diagram' : 'code',
        source, language, spans: language === 'mermaid' ? [] : [{ text: source, code: true }] });
    } else if (token.type === 'hr') blocks.push({ kind: 'rule', spans: [], ...context() });
    else if (token.type === 'table_open') {
      const rows: TextSpan[][][] = [];
      const alignments: Array<'left' | 'center' | 'right'> = [];
      let row: TextSpan[][] = [], column = 0;
      while (++i < tokens.length && tokens[i].type !== 'table_close') {
        const cell = tokens[i];
        if (cell.type === 'tr_open') { row = []; column = 0; }
        else if (cell.type === 'th_open') {
          const alignment = /text-align:(left|center|right)/.exec(String(cell.attrGet('style') || ''))?.[1];
          alignments[column] = (alignment as 'left' | 'center' | 'right') || 'left';
        } else if (cell.type === 'inline') { row.push(inlineSpans(cell.children || [])); column++; }
        else if (cell.type === 'tr_close') rows.push(row);
      }
      blocks.push({ kind: 'table', spans: [], rows, alignments, ...context() });
    }
  }
  return blocks;
}
